services:
  php:
    build: ./docker/php
    ports:
      - 80:80
    volumes:
      - ./web:/var/www/html
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
    links:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:8.0
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=app"
    ports:
      - "33061:3306"
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
        - PMA_HOST=mysql
        - PMA_USER=user
        - PMA_PASSWORD=secret
        - UPLOAD_LIMIT=64M
      restart: always
      ports:
        - 8081:80